### ISSUE TITLE
Call R from C#

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1600]

**Comment by int19h** [comment]
What's the connection with R markdown (#1158)?

**Comment by MikhailArkhipov** [comment]
Wrong link. Should be #1598

**Comment by Hong-Revo** [comment]
I guess you guys are aware of R.NET?

http://jmp75.github.io/rdotnet/index.html

**Comment by MikhailArkhipov** [comment]
Yes. However, some users expressed concerns. Specifically

a. The library doesnt appear to be actively maintained. Last commit was 1.5 years ago.
b. It seems to load R.dll in process. R crash brings down the app.
c. Not entirely sure about using the library in multithreaded code.
d. Some users said R.NET is explicitly forbidden in their companies. I don't know why.

**Comment by Hong-Revo** [comment]
Hm, does this mean you're looking at making a replacement, developed in-house by Microsoft, for R.NET?

That sounds really cool, and would be what many people expect from MS. But is it something specifically related to RTVS?

I guess I'm just curious why this is an issue in the RTVS repo.

**Comment by MikhailArkhipov** [comment]
No, not even remotely like R.NET. Just a tiny wrapper (single interface) over components (packaged into nuget) that we already have. There is active PR you can look at the interface.

**Comment by MikhailArkhipov** [comment]
Will be published to nuget when 1.0 is out along with the doc and samples

**Comment by MikhailArkhipov** [comment]
Sample code repo https://github.com/MikhailArkhipov/RTVS-cs

**Comment by MikhailArkhipov** [comment]
https://www.nuget.org/packages/Microsoft.R.Host.Client.API/1.0.0
https://github.com/MikhailArkhipov/RTVS-cs

**Comment by minuz** [comment]
Hi @MikhailArkhipov, is there a dotnet core version or a plan to port it dotnet core?

**Comment by MikhailArkhipov** [comment]
We ported core component to .NET Core in master so yes, when we update to 1.2 I can probably make .NET Standard 1.6 package.

**Comment by jmp75** [comment]
Hi, I only came across this thread today, as I was pushing a minor update for the [R.NET nuget package](https://www.nuget.org/packages/R.NET).  I am interested to see these developments from Microsoft, and would welcome suggestions as to how to complement features. For a start my current paid job is mostly  C++/Python, so while I'd like to maintain contributions to R/.NET interop I cannot afford duplicated effort, unpaid and personal.

The original dot-points in this thread about R.NET are a tad disingenuous in my view and disappointingly reminiscent of old tactics, but I'd prefer to leave it aside and see if there is a constructive collaborative way forward.

**Comment by MikhailArkhipov** [comment]
We don't have anything against R.NET, it is a great package. However, we use different approach to running R and some prefer it this way. Out packages is a very lightweight API over RTVS infrastructure. It is nowhere as rich as R.NET and is not intended to be a replacement or even a competition. the API is limited to calling existing R functions and returning results as list or a data frame or a plot. That is about it.

We run R out of process and also support running R and executing code on a remote machine (this also can be a Docker container). Current NuGet package does not implement remote connectivity as RTVS does in the VS IDE but it will be updated at some point.

**Comment by alexzaytsev-newsroomly** [comment]
@MikhailArkhipov Does Microsoft.R.Host.Client.API require installation of VS? Or RTVS? Microsoft R? Or just open source R? With .net core, will it run on linux with open source R?

**Comment by MikhailArkhipov** [comment]
It does not require VS or RTVS. All components necessary are packaged in nuget. CRAN R is fine. You may also need 2015 C runtime according to some reports - vsruntime14.dll I believe.

**Comment by waimoelwin** [comment]
awesome bro..... i have been stacking for days by trying RTool, RDotNet to merge C# and R.

Now solved it with ur R API Test.

**Comment by waimoelwin** [comment]
library(quantmod)
symbol <- "ACN"
Accenture_financial_data <- getFinancials(symbol,auto.assign=FALSE)
dataset_annual<-data.frame(Accenture_financial_data$IS$A)

I am trying to get the dataset_annual from your API console. But it doesn't show anything. Can you help me?

I am running the code line by line by pressing Execute button.

**Comment by waimoelwin** [comment]
the problem is that quantmod package is not installed yet.

I try to run the following command. But cannot run and got the error.
install.packages('zoo',repos='http://cran.stat.nus.edu.sg')

**Comment by waimoelwin** [comment]
Hi Sir,
I have found out that your R Api Test to run R codes with Microsoft.R.Host.Client can only run R codes up to 50 rows. R objects from the lines after 50, cannot retrieve anymore. Is there any way to increase the limit sir.

Regards,

**Comment by MikhailArkhipov** [comment]
Not sure about 50 lines limit. There is no limit on the code you can source and run. Or do you mean returned data? If you mean console output, it is limited per R settings, consider https://stackoverflow.com/questions/6758727/how-to-increase-the-limit-for-max-print-in-r

**Comment by waimoelwin** [comment]
@MikhailArkhipov  

I don't mean for print function Sir.
I mean if I input morethan 50 lines in execution , for example

a1 <- 1
a2 <- 2
....
.....
.....
a49 <-  49
a50 <- 50
a51 <- 51

after a50 , the input affect no more.
I can retrieve the data of until a50 but after a50; a51, a52, cannot retrieve.

**Comment by waimoelwin** [comment]
Dear Sir @MikhailArkhipov 

I don't mean for the print function. 

I attached the R script file in below.
That's working well in R studio with Ctrl+A  (Run) and can run in Rtools (R Project in VS) as well.

However If I put all of them in ur API Test window console, I can only retrieve data until row 50.
Codes after row 50, don't affect anymore. I debugged ur console program and see the result when I put (select All of) my codes and click execute button. No error output is detected. 

Just cannot retrieve the data start from row 51.

I checked the R codes several times for error clearance.




[ScriptForMikhali.txt](https://github.com/Microsoft/RTVS/files/1456411/ScriptForMikhali.txt)

**Comment by MikhailArkhipov** [comment]
RTVS sends large code blocks line by line. There may be a limit on how much R accepts in a single chunk for evaluation. You can simply place large code into a file and instead execute `source('myfile.r')` instead of the block.

Also, you may want to file issues/questions in https://github.com/MikhailArkhipov/Rtvs-cs rather than here since this issue is closed.

**Comment by rsbavaresco** [comment]
Is there any plan to publish .Net Standard 1.6+ support? 
Thanks

**Comment by rsbavaresco** [comment]
Hi @MikhailArkhipov ,
Is there any plan to publish .Net Standard 1.6+ package support?
Thanks

**Comment by Dolgih-Nastya** [comment]
Hi @MikhailArkhipov, thank you very much for RTVS! It is really the best way to connect R to C# app. I've tried other libraries to do it: R.NET, RServe and some others, but I always had many troubles with them. RTVS is very convenient and effective. Thank you! Спасибо :)
